### ISSUE TITLE
Feature request: custom van der Waals radii files?

### ISSUE THREAD

**Issue by yummy-hat** [joshua-mae/HoleHelper#8]
My understanding of Hole is that you need to specify the vdw radius for all the atoms involved in the calculation. So if you care about the surface of anything that isn't a standard amino acid, you may need to create a new .rad file (see docs [here](https://www.holeprogram.org/doc/old/hole_d05.html)). 

This may be nitpicky, but e.g. I'm using CHARMM36 for my simulations, so my vdw radii don't correspond to exactly what's in simple2.rad. 

I also think the .rad file format is a little clunky, so I think users would like to avoid making their own custom .rad files. 

So here's the request: would you be interested in supporting custom .rad files with your plugin? Here are two possibilities:
- Some sort of file creation wizard where the user can manually enter parameters for each atom type, and a proper .rad file is created for use with HOLE
- More complicated, but something more automatic: given the PSF/PDB (which you are already reading) and some input parameter files, do what NAMD does and automatically read the radii for each atom type. Then create a comprehensive input file for HOLE. Could be useful to e.g. compare HOLE profiles for the same simple system in different force fields (CHARMM vs. AMBER, etc.). 

I don't know much about psfgen/VMD, but this kind of functionality (getting all the radii for each atom in the loaded molecule) probably already exists. Could be a unique way for you to exploit the power of VMD in running HOLE.

**Comment by joshuamae** [comment]
You mentioned your custom `.rad` file worked with Hole.  Could I just make an option for someone to put in their own `.rad` file? I would assume a majority don't need a custom `.rad` file since I am just following what is offered in the MDAnalysis version.  The creation wizard could be interesting to explore, but I don't know if I have the time to relearn everything.  The second option is probably out of the picture since I barely learned how to use VMD during the time I made this and never really got into NAMD.

Addendum: You can put your custom file in the `rad` folder and rename it to the default options as a temp solution.

**Comment by yummy-hat** [comment]
Hey, thanks for the response and sorry I didn't see it until now! Yes, just having the option to use your own file would solve everything, I think. Not super high priority. Thanks again for the plugin.
